name: Python - Test coverage

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check test coverage with Python ${{ matrix.python-version }}
      run: |
        pip install coverage
        coverage run -m pytest
        coverage report --fail-under=90